account_id = "bc4564dd499c0a9b8a7bb79c9bd5ea6d"
name = "personal-website"
type = "webpack"
route = "georgeblack.me/*"
workers_dev = false
zone_id = "4a21548be8c0b23b8101c86314f4e413"

[site]
bucket = "./src"
entry-point = "workers-site"
