name: 'Download from GCS'
description: 'Simple download from GCS'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  gcloudProjectId:
    description: 'Google Cloud project ID'
    required: true
  gcloudServiceAccount:
    description: 'Email of Google Cloud service account to deploy service'
    required: true
  gcsUri:
    description: 'The GCS URI to download from, i.e. gs://my-bucket/some-files'
    required: true
  localPath:
    description: 'Local path to download to, i.e. /path/to/dir'
    required: true
