name: 'Cloud Run Deploy'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  projectId:
    description: 'Google Cloud project ID'
    required: true
  bucketName:
    description: 'Name of GCS bucket'
