name: 'Jekyll Build'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  sourceDirectory:
    description: 'Directory in your GitHub workspace containing Jekyll site'
    required: true
  outputDirectory:
    description: 'Directory in which build will output'
    required: false
