name: Lint
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
      - name: golang-nilaway
        uses: georgemblack/actions/golang-nilaway
        with:
          package: ./pkg/*
