name: Build and Publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download Assets from GCS
        uses: ./.github/actions/gcs-download
        with:
          gcloudProjectId: ${{ secrets.GCLOUD_PROJECT_ID }}
          gcloudServiceAccount: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
          gcsUri: gs://georgeblack-public/web/assets/gen
          localPath: ./src/assets
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Run Preprocessor
        uses: georgemblack/actions/yarn-command@1.0.0
        with:
          command: build
      - name: Jekyll Build
        uses: ./.github/actions/jekyll-build
        with:
          sourceDirectory: src
      - name: Upload Artifact to GCS
        uses: ./.github/actions/gcs-artifact-upload
        with:
          gcloudProjectId: ${{ secrets.GCLOUD_PROJECT_ID }}
          gcloudServiceAccount: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
          gcsUri: gs://georgeblack-archive/personal-website
          localPath: ./src/_site
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
