name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Preprocessor
        uses: georgemblack/actions/yarn-command@1.0.6
        with:
          command: build
      - name: Jekyll Build
        uses: georgemblack/actions/jekyll-build@1.0.8
        with:
          directory: src
          outputDirectory: dist
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
