name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Preprocessor
        uses: georgemblack/actions/yarn-command@1.0.0
        with:
          command: build
      - name: Jekyll Build
        uses: georgemblack/actions/jekyll-build@1.0.0
        with:
          sourceDirectory: src
      - name: Sync to GCS
        uses: ./.github/actions/gsc-rsync
        with:
          projectId: ${{ secrets.GCLOUD_PROJECT_ID }}
          bucketName: ${{ secrets.GCLOUD_BUCKET_NAME }}
        env:
           GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
