name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Preprocessor
        uses: georgemblack/actions/yarn-command@1.0.4
        with:
          command: build
          directory: sites/main
      - name: Jekyll Build
        uses: ./.github/actions/jekyll-build
        with:
          sourceDirectory: sites/main/src
          outputDirectory: dist
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
