allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
patchedDependencies:
  astro@7.2.0: patches/astro@7.2.0.patch
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
